"""AI-powered runbook generation."""

from __future__ import annotations

import os
from pathlib import Path
from datetime import date

from runbookgen.core.config import RunbookConfig, RUNBOOK_SECTIONS
from runbookgen.core.extractor import ServiceContext


def generate_runbook(context: ServiceContext, config: RunbookConfig) -> str:
    """Generate a runbook using the Anthropic API."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _fallback_runbook(context, config)

    try:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)

        sections = "\n".join(f"- {s}" for s in RUNBOOK_SECTIONS)
        prompt = f"""You are a senior SRE writing an operational runbook for a {config.industry} engineering team.

Generate a comprehensive operational runbook based on the following service context.

Service name: {context.service_name}
Industry: {config.industry}
Compliance context: {config.industry_context}

Source context:
{context.truncated(config.max_input_lines)}

Generate a runbook with these sections:
{sections}

Requirements:
- Be specific to the actual service context provided
- Include realistic alert thresholds and remediation steps
- Add compliance notes relevant to {config.industry}
- Include escalation paths and rollback procedures
- Write for an on-call engineer who may be unfamiliar with the service
- Format as clean Markdown with clear headers
- Include a revision history table at the end

Do not add generic filler. Every section should reflect the actual service context."""

        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        return message.content[0].text

    except Exception:
        return _fallback_runbook(context, config)


def _fallback_runbook(context: ServiceContext, config: RunbookConfig) -> str:
    """Structured fallback runbook when API is unavailable."""
    today = date.today().isoformat()
    sections = "\n\n".join(
        f"## {section}\n\n_TODO: Complete this section_"
        for section in RUNBOOK_SECTIONS
    )
    return f"""# {context.service_name} — Operational Runbook

> Generated by runbook-gen | Industry: {config.industry} | Date: {today}

{sections}

## Revision history

| Date | Author | Change |
|------|--------|--------|
| {today} | runbook-gen | Initial generation |
"""


def write_runbook(content: str, config: RunbookConfig) -> Path:
    """Write a runbook to the output directory."""
    output_dir = Path(config.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{config.service_name.replace(' ', '-').lower()}-runbook.md"
    output_path = output_dir / filename
    output_path.write_text(content)
    return output_path